### ISSUE TITLE
Bootstrap styles dont work 

### ISSUE THREAD

**Issue by maciej2303** [LaravelDaily/laravel-invoices#42]
It was working earlier. I tried  
`<link rel="stylesheet" href="{{ public_path('/vendor/invoices/bootstrap.min.css') }}">`
`<link rel="stylesheet" href="{{ asset('/vendor/invoices/bootstrap.min.css') }}">`
or even Cdn link. Nothing work in stream() also in dowload.

**Comment by PovilasKorop** [comment]
@maciej2303 yes exactly, so something is wrong with loading CSS in general, we didn't change anything on our side, so maybe Laravel changed something. Will investigate.

**Comment by steph1902** [comment]
hi, is there any update about this? because mine didn't work too

**Comment by steph1902** [comment]
![image](https://user-images.githubusercontent.com/45784752/93838973-9a866300-fcb5-11ea-957a-a0ccfa000ad3.png)
looks like this

**Comment by PovilasKorop** [comment]
@steph1902 no update yet, it's on our schedule for later this week. Or maybe you would suggest a solution quicker?

**Comment by steph1902** [comment]
I see, I have no idea and even not sure, as far as I know, generating html and css to pdf is kinda tricky, because pdf only recognize some css, knowing that it's possible to use bootstrap to generated pdf is new to me
I also already tried with cdn, or use the bootstrap css in my project but still not loaded, the view is as I upload before..

**Comment by Marius-K** [comment]
@maciej2303 @steph1902 The bug has been fixed. Please update package to the latest version (`composer update laraveldaily/laravel-invoices`)

Also, view template has been modified so you need to republish it (`php artisan invoices:update`) or make changes by yourself from (commit)[https://github.com/LaravelDaily/laravel-invoices/pull/43/commits/df39278b9d2a70603c08424e46c5375c75961de2#diff-1f279dea35d2a7fe724e94f5f91f086c]

**Comment by jezzdk** [comment]
@Marius-K Can this be merge into v1.3 as well? We're not using Laravel 8 just yet.

**Comment by jouniikaheimo** [comment]
Not working me on version 2.0 laravel 8, or css issue or paper size not working correct pdf show about 50% on paper size

**Comment by jouniikaheimo** [comment]
@Marius-K that 2.0 works fine with laravel 7 too.. i use that...

**Comment by jezzdk** [comment]
> @Marius-K that 2.0 works fine with laravel 7 too.. i use that...

Cool! Thanks :)

**Comment by PovilasKorop** [comment]
@jezzdk I think you can update our package to v2 even in lower versions of Laravel 8, or it doesn't work?

**Comment by ElsaHyseni** [comment]
I updated the package and made the changes, but the styling still doesn't work.

**Comment by jouniikaheimo** [comment]
@ElsaHyseni publish barryvdh/laravel-dompdf config and set show_warnings true now you see why css not working

**Comment by Marius-K** [comment]
> I updated the package and made the changes, but the styling still doesn't work.

Have you tried to clear compiled view files (`php artisan view:clear`)?

**Comment by 007Nil** [comment]
I had faced the same problem. @Marius-K I updated the package and later do the manual changes, does not work on laravel 7. By adding `$this->pdf    = PDF::setOptions(['enable_php' => true, 'enable_remote' => true])->loadHtml($html);` to invoice.php resulting a long reload time.

So I manually add bootstape syles to default.blade.php and it seems working as a temporary solution.

**Bootstrap Table CSS**
`.table {
  width: 100%;
  max-width: 100%;
  margin-bottom: 1rem;
}

.table th,
.table td {
  padding: 0.75rem;
  vertical-align: top;
  border-top: 1px solid #eceeef;
}

.table thead th {
  vertical-align: bottom;
  border-bottom: 2px solid #eceeef;
}

.table tbody + tbody {
  border-top: 2px solid #eceeef;
}

.table .table {
  background-color: #fff;
}

.table-sm th,
.table-sm td {
  padding: 0.3rem;
}

.table-bordered {
  border: 1px solid #eceeef;
}

.table-bordered th,
.table-bordered td {
  border: 1px solid #eceeef;
}

.table-bordered thead th,
.table-bordered thead td {
  border-bottom-width: 2px;
}

.table-striped tbody tr:nth-of-type(odd) {
  background-color: rgba(0, 0, 0, 0.05);
}

.table-hover tbody tr:hover {
  background-color: rgba(0, 0, 0, 0.075);
}

.table-active,
.table-active > th,
.table-active > td {
  background-color: rgba(0, 0, 0, 0.075);
}

.table-hover .table-active:hover {
  background-color: rgba(0, 0, 0, 0.075);
}

.table-hover .table-active:hover > td,
.table-hover .table-active:hover > th {
  background-color: rgba(0, 0, 0, 0.075);
}

.table-success,
.table-success > th,
.table-success > td {
  background-color: #dff0d8;
}

.table-hover .table-success:hover {
  background-color: #d0e9c6;
}

.table-hover .table-success:hover > td,
.table-hover .table-success:hover > th {
  background-color: #d0e9c6;
}

.table-info,
.table-info > th,
.table-info > td {
  background-color: #d9edf7;
}

.table-hover .table-info:hover {
  background-color: #c4e3f3;
}

.table-hover .table-info:hover > td,
.table-hover .table-info:hover > th {
  background-color: #c4e3f3;
}

.table-warning,
.table-warning > th,
.table-warning > td {
  background-color: #fcf8e3;
}

.table-hover .table-warning:hover {
  background-color: #faf2cc;
}

.table-hover .table-warning:hover > td,
.table-hover .table-warning:hover > th {
  background-color: #faf2cc;
}

.table-danger,
.table-danger > th,
.table-danger > td {
  background-color: #f2dede;
}

.table-hover .table-danger:hover {
  background-color: #ebcccc;
}

.table-hover .table-danger:hover > td,
.table-hover .table-danger:hover > th {
  background-color: #ebcccc;
}

.thead-inverse th {
  color: #fff;
  background-color: #292b2c;
}

.thead-default th {
  color: #464a4c;
  background-color: #eceeef;
}

.table-inverse {
  color: #fff;
  background-color: #292b2c;
}

.table-inverse th,
.table-inverse td,
.table-inverse thead th {
  border-color: #fff;
}

.table-inverse.table-bordered {
  border: 0;
}

.table-responsive {
  display: block;
  width: 100%;
  overflow-x: auto;
  -ms-overflow-style: -ms-autohiding-scrollbar;
}

.table-responsive.table-bordered {
  border: 0;
}`

source [https://gist.github.com/luisciphere/3c2d1710d90372784b072ebbcaf7bde4](url)

Hope it helps

**Comment by ElsaHyseni** [comment]
@jouniikaheimo this is the warning i get: "Remote CSS resource 'http://127.0.0.1:8000/vendor/invoices/bootstrap.min.css' referenced, but remote file download is disabled. 'overflow_x' is not a recognized CSS property. '_ms_overflow_style' is not a recognized CSS property."

**Comment by ElsaHyseni** [comment]
@Marius-K I tried that but it still is the same. I had the same problem as @007Nil .  Doing the manual changes resulted in a long reload time.

**Comment by jouniikaheimo** [comment]
@ElsaHyseni "referenced, but remote file download is disabled". You enable that ?

**Comment by ElsaHyseni** [comment]
@jouniikaheimo when I set enable_remote to true, the reload time exceeds 60 seconds.

**Comment by jouniikaheimo** [comment]
> @jouniikaheimo when I set enable_remote to true, the reload time exceeds 60 seconds.

Ah yes.. that is dompdf issue. i think i have a solution to the problem i make pull request tomorrow and  I hope this helps everyone

**Comment by PovilasKorop** [comment]
Ok guys @Marius-K has changed the CSS to load from local instead of remote, and I've released a new 2.x version, can you try and report if the issue is gone? Thanks!

**Comment by ElsaHyseni** [comment]
@PovilasKorop It works now! Thank you so much.

**Comment by maciej2303** [comment]
It works, thanks for all work you did guys.

**Comment by sprklinginfo** [comment]
On Laravel 7.28. After the 'composer update' the invoice package is on 1.3.11. then the template/bootstrap doesn't work anymore. I tried 'php artisan invoices:update' as instructed, but the template still doesn't work. any suggestion? do I need to update to version 2 even I am using Laravel 7? thanks.

**Comment by IvalinV** [comment]
I have the same problem, I'm using v2.0 but the CSS still don't load properly, I've all the proposed solution and nothing works. Any suggestions?
